### ISSUE TITLE
Make Edge work with Gitlab as the upstream

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-edge#183]
### Describe the feature request

I would like to use Edge together with Gitlab.

### Solution suggestions

It might just work, but there's some differences to how gitlab does auth, at the very least we need to find a way to still read tokens that can't be validated.

**Comment by firestonem** [comment]
My org is hitting the Gitlab Unleash rate limit(500 per IP per minute) and would love to use Edge as the solution

**Comment by conorblencowe** [comment]
+1, also looking to use edge in my org

**Comment by bikerp** [comment]
I also appreciate support for GitLab or any suggestion how to proceed with current version

**Comment by chriswk** [comment]
This won't happen until Gitlab upgrades their unleash support, so that we have the endpoints we need to Edge's authentication and metrics process.
