### ISSUE TITLE
service-account-token auto-generates way too many tokens

### ISSUE THREAD

**Issue by sebastian-bury** [Unleash/unleash-edge#236]
### Describe the bug

https://github.com/Unleash/unleash-edge#enterprise
Using the service-account-token to auto-generate tokens as needed creates too many tokens. 

Over the course of 5 days it went from ~550 tokens to over 1500. 

Will update this with more details. 

### Steps to reproduce the bug

1. Use edge with a service-account-token to auto-generate tokens as needed
2. TBD (guess is restarts cause this issue, still identifying) 

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

Edge - connected through with frontend SDKs

**Comment by sighphyre** [comment]
Okay, we know about this one, right now, you should be able to just not use this feature and not get a million tokens. We'll fix at some point soonish and post an update here

**Comment by sighphyre** [comment]
We're partially improved this but not completely fixed it. Edge should no longer generate a few token for every unique front end key. It'll still create new tokens when it restarts though

So we've closed one source of the bug but not the other

**Comment by chriswk** [comment]
So, unless Edge is given a persistent storage, a restart will cause it to generate new tokens. there's no real way to avoid this, since without persistence (file or redis), Edge has no way of remembering the tokens it created.

**Comment by nunogois** [comment]
Some crazy ideas that may lead us to better ones:

How about if Edge cleaned up after itself and deleted the tokens it created when going through safe shutdowns? Kind of like short-lived tokens specific to that Edge instance. This wouldn't cover hard shutdowns though.

We could also introduce the concept of ephemeral tokens, kind of like we have for PATs. Even if Edge opts to create new tokens, old ones would be periodically cleaned up by Unleash.

Even though we could try to leverage upstream Unleash as a sort of persistent storage for Edge, I agree that it is not trivial to solve this without persistency on Edge side.

**Comment by chriswk** [comment]
Another thought I had was that the tokens endpoint in edge should allow us to query for tokens created by us (created by the (serviceaccount/admin) token we use to query for existing tokens)

**Comment by chriswk** [comment]
I'm going to close this one, please feel free to file a feature request for Edge and Unleash to support querying for tokens created by an admin token.
