### ISSUE TITLE
Reload interval do not work in offline mode

### ISSUE THREAD

**Issue by DAGRSAG** [Unleash/unleash-edge#265]
### Describe the bug

Hi all,

I have started a docker image with unleash-edge and provided the environment variable `RELOAD_INTERVAL`. In the Readme I have seen the following hint:

`To make local development easier, you can specify a reload interval in seconds; this will cause Edge to reload the features file from disk every X seconds. This can be useful for local development.`

But unfortunately the reload doesn't work. Toggle is still unchanged until I stop and start the container.

### Steps to reproduce the bug

1. Create a `development.json` with the content
```json
{
	"strategies": [],
	"impressionData": false,
	"enabled": false,
	"name": "pr-auto-add-label",
	"description": "",
	"project": "default",
	"stale": false,
	"type": "release",
	"variants": []
}
```
2. Start unleash-edge with the following command: `docker run -v LOCAL_PATH:/edge/data -p 3063:3063 -e BOOTSTRAP_FILE=/edge/data/development.json -e RELOAD_INTERVAL=5 -e TOKENS=my-secret-123 unleashorg/unleash-edge:v8.0.1 offline`
3. The app connects (Spring boot app) and read the value for `pr-auto-add-label` = false
4. Change the value for enabled from false to true
5. Wait more than 5 seconds
6. The toggle value is still false

### Expected behavior

The value for the toggle should be changed, after reload period, from false to true

### Screenshots

![image](https://github.com/Unleash/unleash-edge/assets/74786365/42690d7b-8d85-45d1-8ddb-44cf59d6643b)

### Unleash version

5.1.8

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

unleash-client-java:7.1.0

**Comment by sighphyre** [comment]
Hey @DAGRSAG! This actually got added in Edge v10.0, which is why you're not seeing it work in your version. Going to close this but this probably need a plan to show which version features were introduced in in our docs. Thanks for raising this!

**Comment by DAGRSAG** [comment]
Hi @sighphyre Thanks for clarifying this. I was indeed not aware of the version clash. 

A short question, before I switch the another version of edge. Are specific version supported / required between edge and server or can I pick any combination of supported versions for edge and the server?
I guess there is no dependency, because I'm using edge 8.x and server 5.x but want to be sure.
