### ISSUE TITLE
Metrics request leads to an issue

### ISSUE THREAD

**Issue by DAGRSAG** [Unleash/unleash-edge#266]
### Describe the bug

Hi,

I have started the unleash-edge in offline mode with the following command:

`docker run -v LOCAL_PATH:/edge/data -p 3063:3063 -e BOOTSTRAP_FILE=/edge/data/development.json -e RELOAD_INTERVAL=5 -e TOKENS=my-secret-123,other-secret-456 unleashorg/unleash-edge:v8.0.1 offline`

Toggles get loaded from json file. But at any point in time, the client (java  sdk) sends a POST request to edge to update metrics. The offline mode do not have metrics at all, which is fine.

But in my Spring Boot application as well in the log of the unleash-edge is an error visible:

docker log from unleash-edge:
![image](https://github.com/Unleash/unleash-edge/assets/74786365/96ae9d1f-bad2-46d6-82a9-76af98a78f99)

Log from Spring boot app:
![image](https://github.com/Unleash/unleash-edge/assets/74786365/674ddaf7-ebce-437e-a6f4-6f469cdde476)

The client doesn't know that the call is send against edge in offline but, but why the edge throws this error? Wouldn't it be possible to just ignore metrics call from sdk?

### Expected behavior

No exception for metrics call from SDK

### Unleash version

5.1.8

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

unleash-client-java:7.1.0

**Comment by chriswk** [comment]
Hi @DAGRSAG - Thanks for the report. Particularly the stack trace from Edge. It caused me to realise what we've done here. All tokens that can be used in Edge mode has an environment, however, in offline mode this is not a guarantee; so I'll update the code to not just assume the environment is set. I'll make a patch on Monday. I'm about to head home for the weekend.

**Comment by DAGRSAG** [comment]
Hi @chriswk. Wow thanks for the fast answers and also for taking care.

Please allow me a question.
In the documentation, I have seen the following: 

> When using offline mode you must specify one or more tokens at startup. These tokens will let your SDKs access Edge. Tokens following the Unleash API format [project]:[environment].<somesecret> allow Edge to recognize the project and environment specified in the token, returning only the relevant features to the calling SDK

But to be honest, I was not successful to use one of the tokens with project and environment. That is the reason, why I just used the token without any further information.

How can I use the token with project (I assume the value from the field within the json file) and the environment? Here is an example from my current json file

```json
{
    "strategies": [],
    "impressionData": false,
    "enabled": false,
    "name": "itk",
    "description": "",
    "project": "default",
    "stale": false,
    "type": "release",
    "variants": []
}
```

Would be nice, if you can give me a hint here

Thanks in advance & best regards
Daniel

**Comment by chriswk** [comment]
Hi again Daniel. 

Good point, we should update the documentation for offline mode. I think you're right, the default features dump does not include environment information, since the features file is different for each environment. 

I'll add another issue (or open it up for you to create a new issue with a request for better documentation for offline) to improve/update the documentation for the offline mode (it has not received much love, since most of our users are using the edge mode.

So, for the next week, we'll make sure that we can handle receiving data without environment. Also, maybe extend the offline mode to configure multiple environments (not currently possible).

**Comment by DAGRSAG** [comment]
I like to complete the triple then and create my third issue 

Ok I assume that already, because I don't find so munch in internet, which is why I have created the issues today. But especially in the dev mode I like the offline mode a lot, because you can quickly change the value without impacting others
