### ISSUE TITLE
Improve documentation for the edge offline mode

### ISSUE THREAD

**Issue by DAGRSAG** [Unleash/unleash-edge#268]
### Describe the feature request

It would be very nice, if you can extend your documentation for the edge offline mode. With the available documentation it was not so easy to get it running. My two main issues are:

## Reload config from json

> To make local development easier, you can specify a reload interval in seconds; this will cause Edge to reload the features file from disk every X seconds. This can be useful for local development.

Not sure if I have done an error on that (see also #265) but I was not able to get it running, that the flags are reloaded without any restart

## Environment/Project handling

> When using offline mode you must specify one or more tokens at startup. These tokens will let your SDKs access Edge. Tokens following the Unleash API format [project]:[environment].secret allow Edge to recognize the project and environment specified in the token, returning only the relevant features to the calling SDK

The question for me is, is it possible to have more than one project / environment for project in this mode? If yes, how to configure those in the json file

And furthermore I tried to use `default.development.my-token` but get a 403 error. If I only use the `my-token`, without any further information, the authentication against edge worked well. (see also https://github.com/Unleash/unleash-edge/issues/266#issuecomment-1721297590)

## Value for `toggle.instance-id`

From my experience, it doesn't matter what or if anything is specified here. However, I searched at the beginning to know if and if so what, I must specify here. I could have saved that if I had known it didn't matter 😄 

With `instance-id` I mean the setting `instanceId` for the sdk.

**Comment by chriswk** [comment]
Hi @DAGRSAG - thanks for your effort in making this issue. Updates to docs coming this week. :+1:
