### ISSUE TITLE
Add a way to pass frontend tokens to unleash-edge in offline mode

### ISSUE THREAD

**Issue by stefanopanella** [Unleash/unleash-edge#298]
### Describe the feature request

It looks like at the moment unleash-edge, when run in offline mode, has one single parameter to accept tokens. It appears as all tokens passed during startup are treated as client SDK tokens, so it is not possible to add tokens to be interpreted as frontend ones.

It would be great to add a new startup parameter to be able to specify frontend tokens.

### Solution suggestions

It would be great to add a new startup parameter to be able to specify frontend tokens.

**Comment by chriswk** [comment]
Note to ourselves, if only tokens parameter is passed, I do believe we'll need to keep current offline behaviour (tokens are valid for both endpoints), however, if you include `--frontend-token` (or whatever the parameter becomes) we should assume tokens are client tokens.

**Comment by chriswk** [comment]
Hi @stefanopanella - This is now live in Edge 19.4.0, you can pass `--client-tokens` and `--frontend-tokens` and Edge should work as the terminal node in a daisy chain

**Comment by stefanopanella** [comment]
@chriswk thanks a lot for taking the time to address this
