### ISSUE TITLE
Exit 1 on hot startup failure

### ISSUE THREAD

**Issue by brtknr** [Unleash/unleash-edge#371]
### Describe the bug

If TOKENS is provided and the bootstrap fails, it appears as though unleash-edge starts anyway. Is it possible to force application to exit so that unleash-edge can retry bootstrapping? We don't want a new unleash-edge deployment to replace the existing if the bootstrapping has failed for whatever reason.

### Subscription type

None

### Hosting type

None

**Comment by sjaanus** [comment]
Hey @brtknr , thank you for contacting us. What tokens are you providing? Are they valid? Do you know why the bootstrap process is failing?

**Comment by brtknr** [comment]
Hi @sjaanus, my thinking around this is if the unleash instance is unavailable and unleash-edge is not able to contact the main unleash server to bootstrap the flags, I don't want my existing deployment to be replace until the new deployment is hot bootstrapped. Does that make sense?

**Comment by sjaanus** [comment]
Sure, in this situation, you should use the edge readiness check. You can find more information about it here: https://docs.getunleash.io/reference/unleash-edge#built-in-ready-check. The edge will become ready as soon as it receives the feature flags. 😊
