### ISSUE TITLE
Document what upstream server versions are expected as part of release

### ISSUE THREAD

**Issue by JonasBak** [Unleash/unleash-edge#396]
### Describe the feature request

Document which versions of the upstream unleash server each new release of unleash-edge expects.

### Background

We use an unleash-hosted Unleash enterprise instance (5.8.1), and I just upgraded unleash-edge from v16.0.3 to v17.0.0.

I see a buch of logs like this:
```
{"timestamp":"2024-01-17T08:09:00.780924Z","level":"INFO","fields":{"message":"Your upstream is outdated. Please upgrade to at least Unleash version 5.9.0 (when ready) or Edge Version 17.0.0 (this one)"},"target":"unleash_edge::http::background_send_metrics"}
{"timestamp":"2024-01-17T08:09:48.734368Z","level":"WARN","fields":{"message":"Connected to an old version of Unleash or Edge. Please upgrade your server to Unleash 5.9 or Edge 17.0"},"target":"unleash_edge::http::unleash_client","span":{"name":"client_token_from_frontend_token"},"spans":[{"name":"client_token_from_frontend_token"}]}
```

### Solution suggestions

It would be nice if these "requirements" were documented as a part of new releases here in the unleash-edge repo, so I know if I should wait until the upstream server is upgraded before I upgrade unleash-edge.

**Comment by sighphyre** [comment]
Hey @JonasBak,

Apologies for the scary warning message here. That was probably little too aggressive on our part. Generally we're committed to making Edge work with any version of Unleash after 4.22. This message is a small warning that there's an optimisation that Edge can and will do if it's talking to a more up to date version of Unleash but it isn't dangerous and can be safely ignored.
