### ISSUE TITLE
Add metrics for failed requests

### ISSUE THREAD

**Issue by lukasz-leszczuk-airspace-intelligence** [Unleash/unleash-edge#412]
### Describe the feature request

I want to know what error status codes (4xx|5xx) were returned by edge, so that I can fine tune monitoring and runbooks.
Currently those are explicitly ommited (https://github.com/Unleash/unleash-edge/blob/d93c28d1a431c24a640ed7013da5fb44d841592f/server/src/metrics/actix_web_metrics.rs#L370), but I believe would still provide much value in speeding up debugging process.

### Solution suggestions

Move metrics update before `if let Ok(res) = res {}` block

**Comment by nunogois** [comment]
Hey @lukasz-leszczuk-airspace-intelligence, thanks for raising this issue! I'll reach out to the rest of the team and we'll get back to you.
