### ISSUE TITLE
Feature flag is not returned from unleash edge frontend API

### ISSUE THREAD

**Issue by mohamedfasil-zee** [Unleash/unleash-edge#416]
It seems to be user not using custom context fields correctly

**Comment by kwasniew** [comment]
@mohamedfasil-zee userType is a custom property. Custom properties should be handled like this: `<base url>/api/frontend?properties%5BuserType%5D=premium&userId=123`
frontend API is very forgiving here and can handle userType that is not nested into custom properties. However Edge is more strict about it.
You'll find which properties are built-in and which are custom here: https://docs.getunleash.io/reference/unleash-context#structure

**Comment by mohamedfasil-zee** [comment]
Thanks a lot @kwasniew 
Closing this issue.

**Comment by mohamedfasil-zee** [comment]
@kwasniew just one point to consider is this behaviour is different on unleash core frontend API vs unleash edge frontend API
FYI
