### ISSUE TITLE
unleash images -  run as non-root user

### ISSUE THREAD

**Issue by talevy-runai** [Unleash/unleash-edge#483]
### Describe the bug

Trying to run unleash edge with RunAsNonRoot security context and gets an error "CreateContainerConfigError"

With the message:
```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  114s                default-scheduler  Successfully assigned runai-backend/runai-backend-unleash-edge-747fc6ccbd-vx9d4 to runai-cluster-worker4
  Normal   Pulled     8s (x10 over 114s)  kubelet            Container image "unleashorg/unleash-edge:v19.1" already present on machine
  Warning  Failed     8s (x10 over 114s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "runai-backend-unleash-edge-747fc6ccbd-vx9d4_runai-backend(f03e42ed-3150-4c34-96f6-485c1ebbe7b2)", container: unleash-edge)
``` 

### Expected behavior

Use a default non-root user in docker image 

### Unleash version

v19.1

### Subscription type

Pro

### Hosting type

Hosted by Unleash

**Comment by chriswk** [comment]
Hi @talevy-runai - I've moved to using the nonroot tagged version of distroless, so with the next release it should be possible to run as non-root

**Comment by talevy-runai** [comment]
@chriswk do you have an estimation of when will be the next release?
