### ISSUE TITLE
Type Error while migrating from proxy to edge : TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by Rookie0031** [Unleash/unleash-edge#521]
### Describe the bug

I use unleash proxy like the code below

In the nextjs app, setting FlagProvider and useFlag to get feature toggle data from the unleash server.

```
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FlagProvider
          config={{
            url: process.env.NEXT_PUBLIC_UNLEASH_PROXY,
            clientKey: process.env.NEXT_PUBLIC_UNLEASH_CLIENT_KEY,
            appName: process.env.NEXT_PUBLIC_UNLEASH_APP_NAME,
            refreshInterval: 1
          }}
        >
          {children}
        </FlagProvider>
      </body>
    </html>
  );
}
```

```
// pages/about.tsx
'use client';

import React from 'react';
import { useFlag} from '@unleash/nextjs/client';

export default function About() {
  const showNewContent = useFlag('declan-test');
  // const showNewContent = true

  return (
    <div>
      {showNewContent ? (
        <div>
          <h1>New Feature Enabled!</h1>
          <p>This is the new content based on the feature toggle.</p>
        </div>
      ) : (
        <div>
          <h1>Lucky You!</h1>
          <p>Have a Good Day</p>
        </div>
      )}
    </div>
  );
}
```

It successfully made requests to unleash-proxy server and get feature toggle data.

But, when I used unleash-edge URL not the proxy, the I faced this problem 

<img width="978" alt="image" src="https://github.com/user-attachments/assets/c52258cd-7544-4927-a652-196f793355ee">

I can find that the request to the unleash server through unleash-edge was successful like the picture below

<img width="1615" alt="image" src="https://github.com/user-attachments/assets/9205c146-31e1-49d2-9002-940f2869957b">

But there is a error while get feature toggle data from the "useFlag"

### Screenshots

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/a8ecbe90-c9b0-43c7-badb-53c9e96159fc">

<img width="1365" alt="image" src="https://github.com/user-attachments/assets/a8e43a07-2dc4-421d-bdb5-0c4ffe1c42a6">

<img width="1625" alt="image" src="https://github.com/user-attachments/assets/e758604e-a3d4-49b2-ad22-ceb5cd420f85">

### Subscription type

None

### Hosting type

None

**Comment by FredrikOseberg** [comment]
Resolved in the community Slack: https://unleash-community.slack.com/archives/CGP2MCHPF/p1725602009150169

Unleash has two endpoints, one for the server side SDKs and one for the frontend clients. These two endpoints retrieves different datasets because on the server the SDKs handle the evaluation there, whereas on the frontend they receive the evaluated toggles to avoid leaking information. An enhancement we can make in the future is to make the SDK smart enough to know when it's getting the incorrect format.
