### ISSUE TITLE
Arm64 builds for Linux

### ISSUE THREAD

**Issue by ccorbacho** [Unleash/unleash-edge#523]
### Describe the feature request

Provide a Linux Arm64 (aarch64) build of Unleash Edge (currently you only provide aarch64 for OS X).

### Background

On most cloud vendors who provide Arm64 (aarch64) nodes (AWS, but Azure, GCP and Oracle cloud are following), the Arm64 nodes are cheaper 10-20% cheaper then the equivalent Intel and AMD nodes, so many businesses are looking to migrate their software to Arm for cost saving.

It would be great if Unleash Edge therefore also provided Linux Arm64 builds to reduce the operational cost.

### Solution suggestions

Extend the target platforms in Cargo.toml to cover aarch64 (Arm64) for Linux (aarch64-unknown-linux-gnu).

**Comment by chriswk** [comment]
True. I'll add this for our next release. We do do build docker container for arm64, but adding the binary build as well shouldn't take too long.

**Comment by ccorbacho** [comment]
It looks like this change got partly rolled back, as 19.5.0 doesn't contain a Linux Arm64 build?

This commit: https://github.com/Unleash/unleash-edge/commit/1090b3b24dfd850f4f13b3775ad5b375f6f5bbea#diff-bb0b53adce565503b53553b212c1edd1f053cc55f643ee35f569cc07f0de3e11

seems to have reverted the Cargo.toml change to add Linux Arm64 to the `targets`?
